name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
      fail-fast: false

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    defaults:
      run:
        shell: bash

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'setup.py'

      - name: Install prerequisites (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install --yes libsnmp-dev snmp-mibs-downloader

      - name: Install prerequisites (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install net-snmp

      - name: Run linter
        run: |
          make lint

      - name: Run tests, with coverage
        run: |
          make test

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
